//
// Created by geri on 2020. 12. 11..
//

#ifndef MULTIPARADIGMAZH_LEAPYEARS_VIZSGALAT_H
#define MULTIPARADIGMAZH_LEAPYEARS_VIZSGALAT_H

int vizsgal(int ev);

#endif //MULTIPARADIGMAZH_LEAPYEARS_VIZSGALAT_H
